feat: add the plugin system to the project
adobe/aem-boilerplate pull request #275
Opened 2023-10-31 14:57 UTC by ramboz

Follow up of #254 that now leverages `aem.js`.

Test URLs:
- Before: https://main--aem-boilerplate--adobe.hlx.live/
- After: https://plugin-system--aem-boilerplate--ramboz.hlx.live/

2023-10-31 19:37 UTC, rofe requested changes
The `aem.js` changes should be in https://github.com/adobe/aem-lib

2023-11-01 07:07 UTC, ramboz commented
@rofe and they are 😉 https://github.com/adobe/aem-lib/pull/23
The changes here are a copy/paste of the aem-lib build from that branch

2023-11-01 10:12 UTC, rofe commented
Ok, then I suggest to let's park this PR until https://github.com/adobe/aem-lib/pull/23 is approved and merged.

2023-11-01 10:35 UTC, ramboz commented
@rofe ok moving it back to a draft PR then

2026-02-04 18:40 UTC, fkakatie commented
Closing this because it's superseded by #374.

2026-02-04 18:40 UTC, closed without merging