[Bug}  Cleanup workflow not working
adobe/aem-boilerplate pull request #344
Opened 2024-04-04 07:43 UTC by gargadobe

Changes:

1. On Branch Creation Github event does not contain head_commit object. Added a conditional statement for same
2. Sometime workflow event is not triggered on branch creation, so added 'workflow_dispatch:' so that it can be manually triggered. 

Fix [#343](https://github.com/adobe/aem-boilerplate/issues/343)

Test URLs:
- Before: https://main--aem-boilerplate--adobe.hlx.live/
- After: https://main--aem-boilerplate--adobe.hlx.live/

2024-04-04 07:46 UTC, gargadobe commented
@tripodsan Please review this

2024-04-04 08:02 UTC, tripodsan requested changes

2024-04-04 08:02 UTC, tripodsan commented on .github/workflows/cleanup-on-create.yaml
> +  workflow_dispatch:
are you sure this works with the trailing `:` ?

2024-04-04 08:10 UTC, gargadobe commented on .github/workflows/cleanup-on-create.yaml
> +  workflow_dispatch:
Yes 

For Reference: https://github.com/orgs/community/discussions/26098#discussioncomment-3250374

2024-04-19 12:22 UTC, trieloff approved these changes

2024-04-19 12:22 UTC, merged